name: Amazon US Beauty Top100

on:
  workflow_dispatch:
  schedule:
    # KST 08:30 ≒ UTC 23:30
    - cron: "12 23 * * *"

env:
  PYTHONUTF8: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  TZ: "Asia/Seoul"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # (선택) pip 캐시 – requirements.txt가 없다면 생략해도 됩니다.
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install \
            requests pandas beautifulsoup4 lxml \
            google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib \
            playwright packaging
          # Playwright + Chromium 및 OS 의존성 자동 설치
          python -m playwright install --with-deps chromium

      - name: Run python app.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python app.py

      - name: Upload CSV artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-csv
          path: data/*.csv
          if-no-files-found: warn
          retention-days: 7
